# Write Kubernetes Deployment Script

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: week08:1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week08_ehg6_user:o77L01CEmZbqq7c5BiMcMD9Iyfd9qsWU@dpg-crfbs9qj1k6c73dk4irg-a.oregon-postgres.render.com/week08_ehg6"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000